CREATE DATABASE Prueba;
USE Prueba;

CREATE TABLE MOVIES
(
	Id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR (50) NOT NULL,
    ReleaseData DATE NOT NULL,
    Genre VARCHAR(50) NOT NULL,
    Price VARCHAR(50) NOT NULL
);